            - имя: Сборка apk
  # Вы можете прикрепить к конкретному коммиту или версии.
  # использует: MirkoMajkicProductDock/BuildAPK@24cc2d17f0c8e391166603bffe50f207b9d75859
  использует: MirkoMajkicProductDock/BuildAPK@v0.0.1
  с:
    # Передайте вкус, для которого вы хотите создать артефакты
    flavor: # необязательно, по умолчанию — release
          
